name: CI Pull Requests
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
      - name: Danger
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
